export const TOGGLE_THEME = "TOGGLE_THEME";

export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
export const SET_WEATHER_DATA = "SET_WEATHER_DATA";
export const SET_FORECAST_WEATHER = "SET_FORECAST_WEATHER";
export const SET_HISTORY_WEATHER = "SET_HISTORY_WEATHER";

export const SET_UNIT = "SET_UNIT";
export const SET_LOADING = "SET_LOADING";
export const SET_IS_USE_ANIMATE_BACKGROUND = "SET_IS_USE_ANIMATE_BACKGROUND";

export const SET_DATA_CHART = "SET_DATA_CHART";
export const SET_IS_SELECTED_COMPARE = "SET_IS_SELECTED_COMPARE";
export const SET_IS_COMPARE = "SET_IS_COMPARE";
export const SET_COMPARE = "SET_COMPARE";
export const ADD_COMPARE = "ADD_COMPARE";

export const SET_POSITIONS = "SET_POSITIONS";
export const SET_CURRENT_POSIITON = "SET_CURRENT_POSIITON";
//
export const apiUrl = "http://localhost:5000/api";
export const LOCAL_STORAGE_TOKEN_NAME = "weather";
